---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erpc.configName" . }}
  labels:
    {{ include "erpc.labels" . | nindent 4 }}
data:
  erpc.yaml: |
    logLevel: {{ .Values.erpc.config.logLevel }}
    {{- if .Values.erpc.config.database }}
    database:
      {{- toYaml .Values.erpc.config.database | nindent 6 }}
    {{- end }}
    server:
      listenV4: true
      httpHostV4: "0.0.0.0"
      listenV6: false
      httpHostV6: "[::]"
      httpPort: {{ .Values.service.port }}
    metrics:
      enabled: true
      listenV4: true
      hostV4: "0.0.0.0"
      listenV6: false
      hostV6: "[::]"
      port: {{ .Values.service.metricsPort }}
    projects:
      {{- toYaml .Values.erpc.config.projects | nindent 6 }}
    {{- if .Values.erpc.config.rateLimiters }}
    rateLimiters:
      {{- toYaml .Values.erpc.config.rateLimiters | nindent 6 }}
    {{- end }}
