---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erpc.configName" . }}
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
data:
  erpc.yaml: |
    logLevel: {{ .Values.erpc.config.logLevel }}
    {{- if .Values.erpc.config.database }}
    {{- with .Values.erpc.config.database.evmJsonRpcCache }}
    {{- if eq .driver "redis" }}
    database:
      evmJsonRpcCache:
        redis:
          addr: {{ .redis.addr }}
          password: >-
            {{ "${" }}ERPC_REDIS_PASSWORD{{ "}" }}
          db: {{ .redis.db }}
    {{- else if eq .driver "memory" }}
    database:
      evmJsonRpcCache:
        maxItems: {{ .maxItems }}
    {{- end }}
    {{- end }}
    {{- end }}
    server:
      {{- toYaml .Values.erpc.config.server | nindent 6 }}
      httpPort: {{ .Values.service.port }}
    metrics:
      {{- toYaml .Values.erpc.config.metrics | nindent 6 }}
      port: {{ .Values.service.metricsPort }}
    projects:
      {{- range $i, $project := .Values.erpc.config.projects }}
      - id: {{ $project.id }}
        {{- with $project.auth }}
        {{- if eq .type "secret" }}
        auth:
          strategies:
            - type: secret
              secret:
                value: >-
                  {{ "${" }}{{ .secretKey }}{{ "}" }}
        {{- end }}
        {{- end }}
        networks:
          {{- range $j, $network := $project.networks }}
          {{- if eq $network.type "evm" }}
          - architecture: evm
            evm:
              chainId: {{ $network.chainId }}
            {{- if $network.failsafe }}
            failsafe:
              {{- toYaml $network.failsafe | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
        upstreams:
          {{- range $i, $upstream := $project.upstreams }}
          - id: {{ $upstream.id }}
            {{- if eq $upstream.type "evm" }}
            type: evm
            evm:
              chainId: {{ $upstream.chainId }}
            {{- end }}
            endpoint: >-
              {{- if $upstream.endpoint.secret.enabled }}
              {{ "${" }}{{ $upstream.endpoint.secret.variable }}{{ "}" }}
              {{- else }}
              {{ $upstream.endpoint.value }}
              {{- end }}
            {{- if $upstream.failsafe }}
            failsafe:
              {{- toYaml $upstream.failsafe | nindent 14 }}
            {{- end }}
          {{- end }}
      {{- end }}
