apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erpc.fullname" . }}
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "erpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.restartOnChanges }}
        values-hash: {{ include "values.hash" . | quote }}
        {{- end }}
      labels:
        {{- include "erpc.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "erpc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.erpc.config.database }}
          {{- with .Values.erpc.config.database.evmJsonRpcCache }}
          {{- if eq .driver "redis" }}
          env:
            - name: ERPC_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.password.secret.name }}
                  key: {{ .redis.password.secret.key }}
          {{- end }}
          {{- end }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.erpc.secret.name }}
          command:
            - /root/erpc-server
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.serviceMonitor.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: erpc-config
              mountPath: /root/erpc.yaml
              subPath: erpc.yaml
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: erpc-config
          configMap:
            name: {{ include "erpc.configName" . }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
