{{- if .Values.ingress.enabled -}}
---
  {{- $baseServiceName := include "common.names.fullname" . -}}
  {{- $routePrefix := .Values.ingress.routePrefix | default "/" -}}
  {{- $defaultPath := list (dict "path" $routePrefix "port" 8000 "pathType" "ImplementationSpecific") -}}
  {{- $paths := .Values.ingress.paths | default $defaultPath -}} 
apiVersion: {{ include "common.capabilities.ingress.apiVersion" $ }}
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.global.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName | default $baseServiceName }}
                port:
                  number: {{ .port }}
          {{- end }}
      {{- with .host }}
      host: {{ . | quote }}
      {{- end }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{ tpl (toYaml . | indent 4) . }}
  {{- end }}
{{- end }}