---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "common.names.fullname" $ }}"
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    pod: "{{ include "common.names.fullname" $ }}"
    app: erpc
  {{- with $.Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 | trim }}
  {{- end }}
  {{- with $.Values.global.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-jsonrpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.erpc.config.server.httpPort }}
      protocol: TCP
    - name: http-metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.erpc.config.metrics.port }}
      protocol: TCP
  selector:
    {{- include "common.labels.matchLabels" $ | nindent 4 }}
    app: erpc
