# Default values for arbitrum-token-bridge
replicaCount: 1

image:
  repository: arbitrum-token-bridge
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: token-bridge.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi


nodeSelector: {}

tolerations: []

affinity: {}

env:
  NEXT_PUBLIC_ETHEREUM_RPC_URL: ""
  NEXT_PUBLIC_ARBITRUM_RPC_URL: ""
  NEXT_PUBLIC_INFURA_KEY: ""
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ""

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5