---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "validator-ejector.fullname" . }}-env-cm
  labels:
    {{- include "validator-ejector.labels" . | nindent 4 }}
data: {{- .Values.config | toYaml | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "validator-ejector.fullname" . }}-loader-env-cm
  labels:
    {{- include "validator-ejector.labels" . | nindent 4 }}
data: {{- .Values.loader.config | toYaml | nindent 2 }}
