apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator-ejector.fullname" . }}
  labels:
    {{- include "validator-ejector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- $svcPorts := concat .Values.service.ports }}
    {{- if $svcPorts }}
    {{- range $port := $svcPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- else }}
    []
    {{- end }}
  selector:
    {{- include "validator-ejector.selectorLabels" . | nindent 4 }}
