---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "validator-ejector.fullname" . }}
  labels:
    {{- include "validator-ejector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "validator-ejector.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "validator-ejector.fullname" . }}
  template:
    metadata:
      annotations:
        configmap-hash: {{ include "configmap.hash" . }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "validator-ejector.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator-ejector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- range $container := .Values.initContainers }}
        - securityContext:
            {{- toYaml $.Values.initContainerSecurityContext | nindent 12 }}
          {{- with $container }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
      containers:
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- /*
        ####################################
        # Validator Ejector Loader
        ####################################
        */}}
        {{- if .Values.loader.enabled }}
        - name: {{ .Release.Name }}-loader
          image: "{{ .Values.loader.image.repository }}:{{ .Values.loader.image.tag }}"
          imagePullPolicy: {{ .Values.loader.image.pullPolicy }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          envFrom:
            - configMapRef:
                name: {{ include "validator-ejector.fullname" . }}-loader-env-cm
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- toYaml .Values.loader.env | nindent 12 }}
            {{- if .Values.global.secretName }}
            - name: EIP2335_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: MESSAGES_PASSWORD
            {{- end }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- else }}
            - name: data
              mountPath: /data
          {{- end }}
          {{- with .Values.loader.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- /*
        ####################################
        # Validator Ejector
        ####################################
        */}}
        - name: {{ .Release.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.workingDir }}
          workingDir: {{ . }}
          {{- end }}
          {{- with .Values.command }}
          command: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{- . | toYaml | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            {{- if .Values.global.secretName }}
            - name: MESSAGES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: MESSAGES_PASSWORD
            {{- end }}
          ports:
          {{- if .Values.service.ports }}
          {{- range $idx, $port := .Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              protocol: {{ $port.protocol }}
          {{- end }}
          {{- else }}
            []
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "validator-ejector.fullname" . }}-env-cm
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- else }}
            - name: data
              mountPath: /data
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if (not .Values.persistence.enabled) }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          {{- include "validator-ejector.labels" . | nindent 10 }}
      spec:
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        accessModes: {{- .Values.persistence.accessModes | toYaml | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
    {{- end }}
