scan:
  skip-dirs:
    - "charts/*/charts"
    - "charts/*/templates/tests"

misconfigurations:
  - id: AVD-KSV-0109
    paths:
      - "**/templates/configmap.yaml"
    statement: "ConfigMap uses environment variable substitution for secrets, not actual values"

  - id: AVD-KSV-0014
    paths:
      - "charon/templates/deployment.yaml"
      - "charon/templates/prometheus-deployment.yaml"
      - "lodestar-vc/templates/statefulset.yaml"
    statement: "Container requires write access to filesystem for operations"

  - id: AVD-KSV-0118
    paths:
      - "charon/templates/deployment.yaml"
    statement: "Custom security context not required for this deployment"

  - id: AVD-KSV-0056
    paths:
      - "charts/validators/templates/role.yaml"
    statement: "Service and pod access required for validator operation"
