apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.ports }}
  {{- range $idx, $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
  {{- end }}
  {{- else }}
    []
  {{- end }}
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }}
