---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- $svcPorts := concat .Values.service.ports .Values.service.extraContainersPorts }}
    {{- if $svcPorts }}
    {{- range $port := $svcPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- else }}
    []
    {{- end }}
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }}
