apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    {{- range $idx, $extraPort := .Values.service.extraPorts }}
    - name: {{ $extraPort.name }}
      port: {{ $extraPort.port }}
      targetPort: {{ $extraPort.name }}
      protocol: {{ $extraPort.protocol }}
    {{- end }}
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }}
