apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- $servicePorts := .Values.service.ports | default list }}
    {{- $extraPorts := .Values.service.extraContainersPorts | default list }}
    {{- if or (gt (len $servicePorts) 0) (gt (len $extraPorts) 0) }}
      {{- range $port := $servicePorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
      {{- end }}
      {{- range $port := $extraPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
      {{- end }}
    {{- else }}
    []
    {{- end }}
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }}
