{{- if .Values.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "validators.fullname" . }}-scripts
  labels:
    {{- include "validators.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/prepare-validator.sh").AsConfig | indent 2 }}
{{- end }}
