---
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  serviceName: {{ include "common.names.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.names.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          command:
            - sh
            - -ac
            - >
              mkdir -p {{ .Values.vouchDataDir }}/{{ include "common.names.fullname" . }}/certs/;
              cp /config/vouch.yaml {{ .Values.vouchDataDir }}/;
              printenv CA_CRT | base64 -d  > {{ .Values.vouchDataDir }}/{{ include "common.names.fullname" . }}/certs/ca.crt;
              printenv CA_KEY | base64 -d  > {{ .Values.vouchDataDir }}/{{ include "common.names.fullname" . }}/certs/ca.key;
              bash /scripts/generate_cert.sh {{ .Values.vouchDataDir }}/{{ include "common.names.fullname" . }}/certs/ ca {{ include "common.names.fullname" . }};
              chown -R {{ .Values.global.podSecurityContext.runAsUser }}:{{ .Values.global.podSecurityContext.fsGroup }} {{ .Values.vouchDataDir }};
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" . }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
        - name: sync-config
          image: "{{ .Values.cliImage.repository }}:{{ .Values.cliImage.tag }}"
          imagePullPolicy: {{ .Values.cliImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" . }}
          args:
          - "sync-vouch-config"
          - "--db-url-env"
          - "ESO_DB_KEYSTORE_URL"
          - "--vouch-dir"
          - "{{ .Values.vouchDataDir }}"
          - "--relays"
          - '{{ join "," .Values.relays }}'
          {{- if .Values.gasLimit }}
          - "--gas-limit"
          - "{{ .Values.gasLimit }}"
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
      containers:
        - name: vouch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" . }}
          args: [ "--base-dir", "{{ .Values.vouchDataDir }}" ]
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: blockrelay
              containerPort: {{ .Values.blockRelayPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
          {{- if .Values.livenessProbe }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
              scheme: {{ .Values.readinessProbe.httpGet.scheme }}
          {{- end }}
        - name: fetch-keys-syncer
          image: "{{ .Values.cliImage.repository }}:{{ .Values.cliImage.tag }}"
          imagePullPolicy: {{ .Values.cliImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" . }}
          args:
          - "sync-vouch-config"
          - "--db-url-env"
          - "ESO_DB_KEYSTORE_URL"
          - "--vouch-dir"
          - "{{ .Values.vouchDataDir }}"
          - "--relays"
          - '{{ join "," .Values.relays }}'
          - "--refresh-frequency"
          - "1800"
          {{- if .Values.gasLimit }}
          - "--gas-limit"
          - "{{ .Values.gasLimit }}"
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: config
          configMap:
            name: {{ include "common.names.fullname" . }}
        - name: scripts
          configMap:
            name: {{ include "common.names.fullname" . }}-scripts
        - name: data
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
