---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aztec-validator.fullname" . }}
  labels:
    {{- include "aztec-validator.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aztec-validator.fullname" . }}-scripts
  labels:
    {{- include "aztec-validator.labels" . | nindent 4 }}
data:
  init.sh: |-
    {{- .Files.Get "files/init.sh" | nindent 4 }}
    {{- .Values.extraInitScript | nindent 4 }}
