{{- range $i := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aztec-validator.fullname" $ }}-p2p-{{ $i }}
  labels:
    type: p2p
    pod: {{ include "aztec-validator.fullname" $ }}-{{ $i }}
    {{- include "aztec-validator.labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ $.Values.service.ports.p2p }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ $.Values.service.ports.p2p }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "aztec-validator.fullname" $ }}-{{ $i }}
    {{- include "aztec-validator.selectorLabels" $ | nindent 4 }}
{{- end }}
