---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aztec-validator.fullname" . }}
  labels:
    {{- include "aztec-validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.internalServiceType }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aztec-validator.selectorLabels" . | nindent 4 }}
