---
# Example InfisicalSecret for ethgas chart using EOA authentication
# This example shows how to use EOA signing key for automatic registration
# Prerequisites:
#   1. Store your EOA signing key in Infisical at the specified secretsPath
#   2. Store CommitBoost JWT token in Infisical
# Note: If using multiple validator pools, use different EOA keys per pool
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ethgas-secret
  namespace: hoodi
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-secrets
        secretNamespace: infisical
      secretsScope:
        projectSlug: angkor
        envSlug: prod
        secretsPath: "/apps/foundation/ethereum/validators"
        recursive: true
  managedKubeSecretReferences:
    - secretName: ethgas-secret
      secretNamespace: hoodi
      creationPolicy: Owner
      secretType: Opaque
      template:
        data:
          # CommitBoost JWT tokens
          CB_JWT_ETHGAS_COMMIT: "{{ .CB_JWT_ETHGAS_COMMIT.Value }}"
          CB_JWTS: "ETHGAS_COMMIT={{ .CB_JWT_ETHGAS_COMMIT.Value }}"
          CB_SIGNER_JWT: "{{ .CB_JWT_ETHGAS_COMMIT.Value }}"
          # EOA signing key for ETHGas Exchange authentication
          EOA_SIGNING_KEY: "{{ .EOA_SIGNING_KEY.Value }}"
  resyncInterval: 60
