---
# Example InfisicalSecret for ethgas chart using JWT authentication
# This example shows how to use pre-generated JWT tokens for ETHGas Exchange
# Prerequisites:
#   1. Generate ACCESS_JWT and REFRESH_JWT tokens via ETHGas Exchange API
#      ref: https://developers.ethgas.com/?http#post-api-v1-user-login
#   2. Store tokens in Infisical at the specified secretsPath
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ethgas-secret
  namespace: hoodi
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-secrets
        secretNamespace: infisical
      secretsScope:
        projectSlug: angkor
        envSlug: prod
        secretsPath: "/apps/foundation/ethereum/validators"
        recursive: true
  managedKubeSecretReferences:
    - secretName: ethgas-secret
      secretNamespace: hoodi
      creationPolicy: Owner
      secretType: Opaque
      template:
        data:
          # CommitBoost JWT tokens
          CB_JWT_ETHGAS_COMMIT: "{{ .CB_JWT_ETHGAS_COMMIT.Value }}"
          CB_JWTS: "ETHGAS_COMMIT={{ .CB_JWT_ETHGAS_COMMIT.Value }}"
          CB_SIGNER_JWT: "{{ .CB_JWT_ETHGAS_COMMIT.Value }}"
          # ETHGas Exchange JWT tokens
          ACCESS_JWT: "{{ .ACCESS_JWT.Value }}"
          REFRESH_JWT: "{{ .REFRESH_JWT.Value }}"
  resyncInterval: 60

