---
# Example InfisicalSecret for Dirk TLS certificates
# Only needed if using Dirk as your remote signer
# If using web3signer or other remote signers, you don't need this
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ethgas-dirk-certs
  namespace: hoodi
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-secrets
        secretNamespace: infisical
      secretsScope:
        projectSlug: angkor
        envSlug: prod
        secretsPath: "/apps/foundation/ethereum/dirk"
        recursive: true
  managedKubeSecretReferences:
    - secretName: ethgas-dirk-certs
      secretNamespace: hoodi
      creationPolicy: Owner
      secretType: Opaque
      template:
        data:
          # Dirk TLS certificates for remote signer connection
          # These should be base64 encoded certificate/key files
          ca.crt: "{{ .DIRK_CA_CRT.Value }}"
          dirk.crt: "{{ .DIRK_CRT.Value }}"
          dirk.key: "{{ .DIRK_KEY.Value }}"
  resyncInterval: 60

