# Example values.yaml configuration when using external secrets (e.g., Infisical)
# This example shows how to configure the ethgas chart to use externally managed secrets

# Reference the external secret created by InfisicalSecret
existingSecret: "ethgas-secret"

# Optional: Only needed if using Dirk as remote signer
# existingDirkSecret: "ethgas-dirk-certs"

# Network and relay configuration (non-sensitive)
ethgas:
  network: "Hoodi"
  rpc_url: "https://ethereum-hoodi-rpc.publicnode.com"
  relays: "https://0xb20c3fe59db9c3655088839ef3d972878d182eb745afd8abb1dd2abf6c14f93cd5934ed4446a5fe1ba039e2bc0cf1011@hoodi-relay.ethgas.com"
  entity_name: "your-entity-name"
  exchange_api_base: "https://hoodi.app.ethgas.com"
  collateral_contract: "0xe8bfB84b14c383b94365a895fc8bfA36dE236dc8"

  # Authentication method: Choose between JWT tokens or EOA signing key
  # Set to true for pre-generated JWT tokens (use infisical-secret-jwt.yaml)
  # Set to false for EOA signing key (use infisical-secret.yaml)
  useJwtAuth: false

  # Remote signer configuration
  # Example for Dirk (uncomment and modify):
  # signer: |
  #   [signer.dirk]
  #   cert_path = "/signer/secrets/dirk.crt"
  #   key_path = "/signer/secrets/dirk.key"
  #   ca_cert_path = "/signer/secrets/ca.crt"
  #
  #   [[signer.dirk.hosts]]
  #   url = "https://dirk-0.example.com:8881"
  #   wallets = ["Validators"]
  #
  # Example for Web3Signer (uncomment and modify):
  # signer: |
  #   [signer.remote]
  #   url = "http://web3signer-url:6174"
  signer: ""

# Service configuration
service:
  type: ClusterIP
  port:
    pbs:
      http: 18550
      metrics: 10000
    signer:
      http: 20000
      metrics: 10001
    ethgas_commit:
      metrics: 10002

# Add resource limits as needed
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
