---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "lodestar.fullname" . }}"
  labels:
    {{- include "lodestar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lodestar.selectorLabels" . | nindent 4 }}
