---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lodestar.fullname" . }}
  labels:
    {{- include "lodestar.labels" . | nindent 4 }}
  annotations:
    trivy.security.devops.aqua.com/KSV014: "Container requires write access for validator keys"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lodestar.selectorLabels" . | nindent 6 }}
  serviceName: "{{ include "lodestar.fullname" . }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lodestar.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lodestar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # trivy:ignore:AVD-KSV-0014
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - "/opt/lodestar/run.sh"
          ports:
            - name: p2p
              containerPort: {{ .Values.service.ports.p2p }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.ports.metrics }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.ports.http }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/lodestar
              name: data
            - mountPath: /keystoresDir
              name: validator-keys
          env:
            {{- toYaml .Values.env | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          configMap:
            name: {{ include "lodestar.fullname" . }}
            defaultMode: 0755
        - name: validator-keys
          persistentVolumeClaim:
            claimName: validator-keys-pvc
