---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aztec-validator.fullname" . }}
  labels:
    {{- include "aztec-validator.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "aztec-validator.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aztec-validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aztec-validator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aztec-validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.initContainerSecurityContext | nindent 12 }}
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          command: ["sh", "-c", "/scripts/init.sh"]
          volumeMounts:
            - name: validator-keys
              mountPath: /app/config/validation_keys
              readOnly: true
            - name: scripts
              mountPath: /scripts/init.sh
              subPath: init.sh
            - name: shared
              mountPath: /shared
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      {{- with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- with $.Values.initContainerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - >
              echo "Starting aztec-validator...";
              . /shared/env;
              echo "EXTERNAL_NODE_IP=${EXTERNAL_NODE_IP}";
              echo "EXTERNAL_NODE_PORT=${EXTERNAL_NODE_PORT}";
              echo "Arguments: {{ join " " .Values.args }}";
              exec node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js {{ join " " .Values.args }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.http }}
              protocol: TCP
            - name: p2p-tcp
              containerPort: {{ .Values.service.ports.p2p }}
              protocol: TCP
            - name: p2p-udp
              containerPort: {{ .Values.service.ports.p2p }}
              protocol: UDP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "aztec-validator.fullname" . }}
            {{- with .Values.envFrom }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- with .Values.env }}
            {{ . | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: shared
              mountPath: /shared
          {{- if or .Values.persistence.enabled .Values.volumeMounts }}
            {{- if .Values.persistence.enabled }}
            - name: {{ include "aztec-validator.fullname" . }}
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      volumes:
        - name: validator-keys
          secret:
            secretName: {{ .Values.validatorKeysSecret }}
        - name: scripts
          configMap:
            name: {{ include "aztec-validator.fullname" . }}-scripts
        - name: shared
          emptyDir: {}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ include "aztec-validator.fullname" . }}
        labels:
          {{- include "aztec-validator.labels" . | nindent 10 }}
      spec:
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        accessModes: {{- .Values.persistence.accessModes | toYaml | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
