---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aztec-prover.fullname" . }}
  labels:
    {{- include "aztec-prover.labels" . | nindent 4 }}
data:
  {{- with include "aztec-prover.config" . | fromYaml }}
  {{- .env | toYaml | nindent 2 }}
  {{- end }}
