---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-scripts
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  init.sh: |
{{ .Files.Get "scripts/init-nodeport.sh" | indent 4 }}
