---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-scripts
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  init.sh: |
{{ tpl (.Files.Get "scripts/init-nodeport.sh") . | indent 4 }}
{{- if and (eq .Values.execution.client "reth") .Values.execution.snapshot.enabled }}
  init-snapshot.sh: |
{{ tpl (.Files.Get "scripts/init-snapshot.sh") . | indent 4 }}
{{- end }}
