{{- if .Values.p2pNodePort.enabled -}}
{{- range $i, $e := until (int .Values.replicaCount) }}
{{- $portExecution := add $.Values.p2pNodePort.startAtExecution $i -}}
{{- $portBeacon := add $.Values.p2pNodePort.startAtBeacon $i -}}
{{- if hasKey $.Values.p2pNodePort.replicaToNodePort ($i | toString) -}}
  {{ $portExecution = index $.Values.p2pNodePort.replicaToNodePort ($i | toString) }}
  {{ $portBeacon = index $.Values.p2pNodePort.replicaToNodePort ($i | toString) }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}-execution-{{ $i }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    pod: "{{ include "common.names.fullname" $ }}-{{ $i }}"
    type: p2p
    client: execution
  {{- with $.Values.p2pNodePort.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.p2pNodePort.type }}
  externalTrafficPolicy: Local
  ports:
    - name: p2p-tcp-exec
      port: {{ include "execution.p2pPort" $ }}
      protocol: TCP
      targetPort: {{ $portExecution }}
      nodePort: {{ $portExecution }}
  {{- if eq $.Values.p2pNodePort.type "NodePort" }}
    - name: p2p-udp-exec
      port: {{ include "execution.p2pPort" $ }}
      protocol: UDP
      targetPort: {{ $portExecution }}
      nodePort: {{ $portExecution }}
    {{- if and (eq $.Values.execution.client "reth") $.Values.execution.enableDiscoveryV5 }}
    - name: discv5-udp-exec
      port: {{ add (include "execution.p2pPort" $ | int) 2 }}
      protocol: UDP
      targetPort: {{ add $portExecution 2 }}
      nodePort: {{ add $portExecution 2 }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "common.names.fullname" $ }}-{{ $i }}"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}-beacon-{{ $i }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    pod: "{{ include "common.names.fullname" $ }}-{{ $i }}"
    type: p2p
    client: beacon
  {{- with $.Values.p2pNodePort.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.p2pNodePort.type }}
  externalTrafficPolicy: Local
  ports:
    - name: p2p-tcp-beacon
      port: {{ include "beacon.p2pPort" $ }}
      protocol: TCP
      targetPort: {{ $portBeacon }}
      nodePort: {{ $portBeacon }}
  {{- if eq $.Values.p2pNodePort.type "NodePort" }}
    - name: p2p-udp-beacon
      port: {{ include "beacon.p2pPort" $ }}
      protocol: UDP
      targetPort: {{ $portBeacon }}
      nodePort: {{ $portBeacon }}
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "common.names.fullname" $ }}-{{ $i }}"

{{- end }}
{{- end }}
