defaultAlertLabels: {}

spec:
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert
      expr: Vector(1)
      for: 5m
      labels:
        # The severity label is mandatory for alerts (not records). We recommend either warning or critical
        severity: warning
