template-sts:
	helm template generic-sts . -f values.yaml -f values.sts.yaml --debug > manifest.yaml

template-deploy:
	helm template generic-deploy . -f values.yaml -f values.deploy.yaml --debug > manifest.yaml

template-p2p:
	helm template generic-p2p . -f values.yaml -f values.p2p.yaml --debug > manifest.yaml
