---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dirk.fullname" . }}
  labels:
    {{- include "dirk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dirk.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "dirk.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dirk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "dirk.selectorLabels" . | nindent 14 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dirk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          command:
            - bash
            - -xc
            - >
              apk add openssl envsubst;
              rm -f /data/dirk/dirty;
              mkdir -p /data/dirk/certs;
              export INDEX=$((${HOSTNAME##*-}+1));
              echo "$INDEX" > /data/dirk/index;
              envsubst < /config/dirk.yaml.tml > /data/dirk/dirk.yaml;
              printenv dirk-ca.crt | base64 -d  > /data/dirk/certs/ca.crt;
              printenv dirk-ca.key | base64 -d  > /data/dirk/certs/ca.key;
              bash /scripts/generate_cert.sh /data/dirk/certs/ ca ${HOSTNAME}.{{ include "dirk.fullname" . }};
              chown -R {{ .Values.global.podSecurityContext.runAsUser }}:{{ .Values.global.podSecurityContext.fsGroup }} /data/dirk;
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
        - name: fetch-keys
          image: "{{ .Values.cliImage.repository }}:{{ .Values.cliImage.tag }}"
          imagePullPolicy: {{ .Values.cliImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "dirk.fullname" . }}-env
          {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
          - "sync-dirk-keys"
          - "--db-url-env"
          - "ESO_DB_KEYSTORE_URL"
          - "--wallet-dir"
          - "/data/dirk"
          - "--decryption-key-env"
          - "ESO_DECRYPTION_KEY"
          {{- range .Values.dirk.fetchKeysExtraFlags }}
          - {{ . | quote }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: dirk
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args: [ "--base-dir", "/data/dirk" ]
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
              scheme: {{ .Values.readinessProbe.httpGet.scheme }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
        - name: fetch-keys-syncer
          image: "{{ .Values.cliImage.repository }}:{{ .Values.cliImage.tag }}"
          imagePullPolicy: {{ .Values.cliImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "dirk.fullname" . }}-env
          {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
#          command: [ "/bin/bash", "-c", "--" ]
#          args: [ "while true; do sleep 30; done;" ]
          args:
          - "sync-dirk-keys"
          - "--db-url-env"
          - "ESO_DB_KEYSTORE_URL"
          - "--wallet-dir"
          - "/data/dirk"
          - "--decryption-key-env"
          - "ESO_DECRYPTION_KEY"
          - "--refresh-frequency"
          - "1800"
          {{- range .Values.dirk.fetchKeysExtraFlags }}
          - {{ . | quote }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: config
          configMap:
            name: {{ include "dirk.fullname" . }}
        - name: scripts
          configMap:
            name: {{ include "dirk.fullname" . }}-scripts
  minReadySeconds: {{ .Values.minReadySeconds }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "dirk.labels" . | nindent 10 }}
      {{- with .Values.persistence.annotations }}
        annotations:
          {{ toYaml . | nindent 10 | trim }}
      {{- end }}
      spec:
        accessModes: {{ .Values.persistence.accessModes }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
