apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  config.yaml: |
    data-path: "/data/web3signer"
    key-store-path: "/data/keystore"
    eth2.network: {{ .Values.network }}
    logging: {{ .Values.loggingLevel }}
    eth2.slashing-protection-enabled: true
    eth2.slashing-protection-pruning-enabled: true
    eth2.slashing-protection-pruning-epochs-to-keep: {{ .Values.pruningEpochToKeep }}
    eth2.slashing-protection-pruning-interval: {{ .Values.pruningInterval }}
    eth2.slashing-protection-pruning-slots-per-epoch: {{ .Values.slotsPerEpoch }}
    metrics-enabled: true
    metrics-host: "0.0.0.0"
    metrics-port: {{ .Values.metricsPort }}
    metrics-host-allowlist: ["*"]
    swagger-ui-enabled: true
    http-cors-origins: ["*"]
    http-listen-host: "0.0.0.0"
    http-listen-port: {{ .Values.httpPort }}
    http-host-allowlist: ["*"]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-migrations
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
{{ $root := . }}
{{- range $path, $_ :=  .Files.Glob  "migrations/**.sql" }}
{{- with $root }}
  {{ $path | replace "migrations/" ""}}: |-
{{ .Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
