{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  ESO_DECRYPTION_KEY: {{ .Values.secrets.decryptionKey | b64enc }}
  ESO_DB_KEYSTORE_URL: {{ .Values.secrets.dbKeystoreUrl | b64enc }}
  ESO_DB_URL: {{ .Values.secrets.dbUrl | b64enc }}
  ESO_DB_USERNAME: {{ .Values.secrets.dbUsername | b64enc }}
  ESO_DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc }}
{{- end }}
