{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: eso-{{ include "common.names.fullname" . }}
    creationPolicy: Owner
  data:
  {{- if empty .Values.externalSecrets.data }}
    - secretKey: ESO_DECRYPTION_KEY
      remoteRef:
        key: {{ .Values.global.label }}-external-secrets
        property: decryptionKey
    - secretKey: ESO_DB_KEYSTORE_URL
      remoteRef:
        key: {{ .Values.global.label }}-external-secrets
        property: dbKeystoreUrl
    - secretKey: ESO_DB_URL
      remoteRef:
        key: {{ .Values.global.label }}-external-secrets
        property: dbUrl
    - secretKey: ESO_DB_USERNAME
      remoteRef:
        key: {{ .Values.global.label }}-external-secrets
        property: dbUsername
    - secretKey: ESO_DB_PASSWORD
      remoteRef:
        key: {{ .Values.global.label }}-external-secrets
        property: dbPassword
  {{- else }}
  {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  ESO_DECRYPTION_KEY: {{ .Values.secrets.decryptionKey | b64enc }}
  ESO_DB_KEYSTORE_URL: {{ .Values.secrets.dbKeystoreUrl | b64enc }}
  ESO_DB_URL: {{ .Values.secrets.dbUrl | b64enc }}
  ESO_DB_USERNAME: {{ .Values.secrets.dbUsername | b64enc }}
  ESO_DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc }}
{{- end }}
