apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  serviceName: {{ include "common.names.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web3signer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          command:
            - sh
            - -ac
            - >
              mkdir -p /data/web3signer /data/keystore;
              chown -R {{ .Values.global.podSecurityContext.runAsUser }}:{{ .Values.global.podSecurityContext.fsGroup }} /data/web3signer;
              mkdir -p /opt/web3signer/file-uploads;
              chown -R {{ .Values.global.podSecurityContext.runAsUser }}:{{ .Values.global.podSecurityContext.fsGroup }} /opt/web3signer/file-uploads
          volumeMounts:
            - name: data
              mountPath: /data
        - name: migrations
          image: "{{ .Values.flywayImage.repository }}:{{ .Values.flywayImage.tag }}"
          imagePullPolicy: {{ .Values.flywayImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          args:
            - -user=$(DB_USERNAME)
            - -password=$(DB_PASSWORD)
            - -url=$(DB_URL)
            - migrate
          envFrom: {{- tpl (toYaml .Values.envFrom) $ | nindent 12 }}
          env: {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: migrations
              mountPath: /flyway/sql
        - name: fetch-keys
          image: "{{ .Values.cliImage.repository }}:{{ .Values.cliImage.tag }}"
          imagePullPolicy: {{ .Values.cliImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          envFrom: {{- tpl (toYaml .Values.envFrom) $ | nindent 12 }}
          env: {{- toYaml .Values.env | nindent 12 }}
          args: ["sync-web3signer-keys", "--db-url", $(DB_KEYSTORE_URL), "--output-dir", "/data/keystore", "--decryption-key-env", "DECRYPTION_KEY"]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10000
            capabilities:
              drop:
              - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config-file=/config/config.yaml
            - --logging={{ .Values.loggingLevel }}
            - --idle-connection-timeout-seconds={{ .Values.idleTimeout }}
            - eth2
            - --slashing-protection-db-url=$(DB_URL)
            - --slashing-protection-db-username=$(DB_USERNAME)
            - --slashing-protection-db-password=$(DB_PASSWORD)
          env:
            - name: JAVA_OPTS
              value: {{ .Values.web3signerJavaOpts | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom: {{- tpl (toYaml .Values.envFrom) $ | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /upcheck
              port: http
            initialDelaySeconds: 900
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /upcheck
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
        {{- if .Values.enableReloader }}
        - name: fetch-keys-reloader
          image: "{{ .Values.cliImage.repository }}:{{ .Values.cliImage.tag }}"
          imagePullPolicy: {{ .Values.cliImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          envFrom: {{- tpl (toYaml .Values.envFrom) $ | nindent 12 }}
          env: {{- toYaml .Values.env | nindent 12 }}
          args: ["sync-web3signer-keys", "--db-url", $(DB_KEYSTORE_URL), "--output-dir", "/data/keystore", "--decryption-key-env", "DECRYPTION_KEY", "--refresh-frequency", "60"]
          volumeMounts:
            - name: data
              mountPath: /data
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.names.fullname" . }}
        - name: migrations
          configMap:
            name: {{ include "common.names.fullname" . }}-migrations
        - name: data
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.tmpfsSize }}
