{{- if .Values.p2p.enabled }}
{{- range $i := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-app-p2p.fullname" $ }}-p2p-{{ $i }}
  labels:
    type: p2p
    pod: {{ include "generic-app-p2p.fullname" $ }}-{{ $i }}
    {{- include "generic-app-p2p.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.p2p.serviceType }}
  ports:
    - port: {{ $.Values.p2p.port }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ $.Values.p2p.port }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "generic-app-p2p.fullname" $ }}-{{ $i }}
    {{- include "generic-app-p2p.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
