{{- if .Values.blockscout.enabled }}
# Redis Deployment for Blockscout
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arbitrum-orbit-chain.fullname" . }}-blockscout-redis
  labels:
    {{- include "arbitrum-orbit-chain.labels" . | nindent 4 }}
    app.kubernetes.io/component: blockscout-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arbitrum-orbit-chain.name" . }}-blockscout-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: blockscout-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arbitrum-orbit-chain.name" . }}-blockscout-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: blockscout-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5

---

# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arbitrum-orbit-chain.fullname" . }}-blockscout-redis
  labels:
    {{- include "arbitrum-orbit-chain.labels" . | nindent 4 }}
    app.kubernetes.io/component: blockscout-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "arbitrum-orbit-chain.name" . }}-blockscout-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: blockscout-redis
{{- end }}
