{{- if .Values.nitro.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orbit-chain.fullname" . }}-nitro-config
  labels:
    {{- include "orbit-chain.labels" . | nindent 4 }}
    app.kubernetes.io/component: nitro
data:
  config.json: |
    {{- .Values.nitro.config | toPrettyJson | nindent 4 }}
{{- end }}
