apiVersion: v2
name: aztec
description: Aztec Prover Node and Prover Agent Helm Chart
type: application
home: https://nethermindeth.github.io/helm-charts
version: 0.0.1
maintainers:
  - name: 0xDones
