---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aztec-prover.fullname" . }}
  labels:
    {{- include "aztec-prover.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
