{{- if .Values.externalSecrets.enabled }}
{{- range $type, $specs := .Values.nodes }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $.Values.externalSecrets.name }}-{{ $type }}"
  {{- with $.Values.global.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: "{{ $.Values.externalSecrets.name }}-{{ $type }}"
    creationPolicy: Owner
  {{- with $specs.secrets.data }}
  data:
    {{- . | toYaml | trim | nindent 2 }}
  {{- end }}
{{- end }}
{{- else }}
{{- range $type, $specs := .Values.nodes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "k8s-espresso-sequencer-secrets-{{ $type }}"
  {{- with $.Values.global.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
type: Opaque
data:
  {{- with $specs.secrets.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
