---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "espresso.serviceAccountName" . }}
  labels:
    {{- include "espresso.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.global.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
{{- end }}
