name: Trivy

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Update Chart Dependencies
        run: |
          for dir in charts/*/; do
            if [ -f "${dir}Chart.yaml" ]; then
              helm dependency update "$dir"
            fi
          done

      - name: Package Charts
        run: |
          WORKSPACE="${GITHUB_WORKSPACE:-$(pwd)}"
          TRIVY_CHARTS_DIR="${WORKSPACE}/.trivy-charts"

          mkdir -p "$TRIVY_CHARTS_DIR"
          for dir in charts/*/; do
            if [ -f "${dir}Chart.yaml" ]; then
              echo "Packaging ${dir} to ${TRIVY_CHARTS_DIR}"
              helm package "$dir" -d "$TRIVY_CHARTS_DIR"
            fi
          done

          echo "Contents of ${TRIVY_CHARTS_DIR}:"
          ls -la "$TRIVY_CHARTS_DIR"

      - name: Run Trivy
        uses: aquasecurity/trivy-action@5681af892cd0f4997658e2bacc62bd0a894cf564 #v0.27.0
        with:
          scan-type: 'fs'
          scan-ref: '${{ github.workspace }}/charts'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          hide-progress: false
          scanners: 'misconfig,secret'
          timeout: '10m'
          version: 'v0.57.0'
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_OCI_REPOSITORY: public.ecr.aws/aquasecurity/trivy-policies
          TRIVY_POLICY_BUNDLE_REPOSITORY: public.ecr.aws/aquasecurity/trivy-checks

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@5618c9fc1e675841ca52c1c6b1304f5255a905a0 #v2.19.0
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'Helm Template Security'
