name: Trivy

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Package Local Dependencies
        run: |
          # Create charts directory for all charts first
          cd charts
          echo "Creating charts directories..."
          for dir in */; do
            if [ -f "${dir}Chart.yaml" ]; then
              mkdir -p "${dir}charts"
              echo "Created charts directory for ${dir}"
            fi
          done

          # Package and move common chart
          echo "Packaging common chart..."
          if [ -d "common" ] && [ -f "common/Chart.yaml" ]; then
            helm package common -d execution-beacon/charts/
            echo "Common chart packaged. Contents of execution-beacon/charts/:"
            ls -la execution-beacon/charts/ || echo "No files yet"
          fi

          # Package and move generic-app chart
          echo "Packaging generic-app chart..."
          if [ -d "generic-app" ] && [ -f "generic-app/Chart.yaml" ]; then
            helm package generic-app
            mv generic-app-*.tgz generic-deployment/charts/
            cp generic-deployment/charts/generic-app-*.tgz generic-statefulset/charts/
            echo "Generic-app chart packaged and moved. Directory contents:"
            echo "generic-deployment/charts/:"
            ls -la generic-deployment/charts/ || echo "No files"
            echo "generic-statefulset/charts/:"
            ls -la generic-statefulset/charts/ || echo "No files"
          fi
          cd ..

      - name: Update Helm Dependencies
        run: |
          for dir in charts/*/; do
            if [ -f "${dir}Chart.yaml" ]; then
              echo "Updating dependencies for $dir"
              helm dependency update "$dir" || echo "No dependencies to update in $dir"
              echo "Contents of ${dir}charts/:"
              if [ -d "${dir}charts" ]; then
                ls -la "${dir}charts/" || echo "Directory empty"
              else
                echo "Charts directory does not exist"
              fi
            fi
          done

      - name: Run Trivy
        uses: aquasecurity/trivy-action@5681af892cd0f4997658e2bacc62bd0a894cf564 #v0.27.0
        with:
          scan-type: 'config'
          scan-ref: './charts'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          skip-dirs: 'charts/*/charts'
          skip-files: '*.tgz'
          hide-progress: false
          scanners: 'config'
          timeout: '10m'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@5618c9fc1e675841ca52c1c6b1304f5255a905a0 #v2.19.0
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'Helm Template Security'
